### ISSUE TITLE
snap-plugin-collector-elasticsearch will not load with snapctl plugin load

### ISSUE THREAD

**Issue by zachary-trudo** [intelsdi-x/snap-plugin-collector-elasticsearch#16]
Problem: Built snap-plugin-collector-elasticsearch from latest [commit](https://github.com/intelsdi-x/snap-plugin-collector-elasticsearch/commit/821fba91323f8766c1d48274208891cb0f89f229
)
When attempting to load snap-plugin-collector-elasticsearch into snap with snapctl plugin load I receive the following error:
```
<029-zwzca:/go/bin# snapctl plugin load snap-plugin-collector-elasticsearch
Error loading plugin:
unexpected EOF
```

Environment:
- snap in tribe mode in kubernetes on gce
- snap plugins loaded:
```
NAME             VERSION         TYPE            SIGNED          STATUS          LOADED TIME
heapster         1               publisher       false           loaded          Fri, 09 Sep 2016 17:09:50 UTC
docker           8               collector       false           loaded          Fri, 09 Sep 2016 17:09:56 UTC
cassandra        3               collector       false           loaded          Fri, 09 Sep 2016 17:10:01 UTC
passthru         1               processor       false           loaded          Fri, 09 Sep 2016 17:09:41 UTC
influx           15              publisher       false           loaded          Fri, 09 Sep 2016 17:09:46 UTC
```

**Comment by candysmurf** [comment]
@zachary-trudo, thanks for showing me how you ran into this error. I think the current plugin requires a global config and when it's not specified, it gave you this. I'll change it to use task manifest and let you know by early next week.

**Comment by obourdon** [comment]
@zachary-trudo your problem is indeed that there is no server defined in the config file

time="2016-09-10T08:21:36+02:00" level=debug msg="2016/09/10 08:21:36 **Cannot find server in Global Config**" _module=plugin-exec io=stderr plugin=snap-plugin-collector-elasticsearch
time="2016-09-10T08:21:36+02:00" level=error msg="error in getting metric types" _block=load-plugin _module=control-plugin-mgr error="unexpected EOF" plugin-type=collector

the other problem is that this is not explicitly exposed as an error message from the plugin due to [this issue in the snap framework](https://github.com/intelsdi-x/snap/issues/1186) but I have had the issue a few months back when I first tried the elasticsearch collector plugin and when plugins had their own log files

I think that it is wrong  to require a plugin to be somehow "configured" at load time, meaning having to specify remote endpoint even though I understand this is a way to retrieve exposed metrics

HTH

**Comment by candysmurf** [comment]
@obourdon, thanks for the confirmation.  The metric types are dynamically collected instead of statically hardcoded that's why it needs the config at the load time. As types most likely won't be changed for a giving version, I'll push an enhancement for it today. You all are welcome to review it. thanks.
